from db_timetable.database import *

with db_session:
    disRus = Discipline(name="Русский язык")
    disMath = Discipline(name="Математика")
    disAlgebra = Discipline(name="Алгебра")
    disGeometry = Discipline(name="Геометрия")
    disGeo = Discipline(name="География")
    disBio = Discipline(name="Биология")
    disHistory = Discipline(name="История")
    disPhysics = Discipline(name="Физика")
    disChemistry = Discipline(name="Химия")
    disArt = Discipline(name="Изобразительное искусство")
    disLiterature = Discipline(name="Литература")
    disMusic = Discipline(name="Музыка")
    disTechnology = Discipline(name="Технология")

    class5A = Class(year="5", litter="A")
    class5B = Class(year="5", litter="Б")
    class5V = Class(year="5", litter="В")
    class6A = Class(year="6", litter="A")
    class6B = Class(year="6", litter="Б")
    class6V = Class(year="6", litter="В")
    class7A = Class(year="7", litter="A")
    class7B = Class(year="7", litter="Б")
    class7V = Class(year="7", litter="В")
    class8A = Class(year="8", litter="A")
    class8B = Class(year="8", litter="Б")
    class8V = Class(year="8", litter="В")

    monday = DayWeek(name="Понедельник")
    tuesday = DayWeek(name="Вторник")
    wednesday = DayWeek(name="Среда")
    thursday = DayWeek(name="Четверг")
    friday = DayWeek(name="Пятница")
    saturday = DayWeek(name="Суббота")

    school = School(name="МКОУ Шатровская средняя школа", address="ул.Федосеева, 72")
    housingA = Housing(name="A", address="ул.Федосеева, 73", school=school)
    housingB = Housing(name="Б", address="ул.Федосеева, 74", school=school)

    cabn1 = Cabinet(number="1", housing=housingA)
    cabn2 = Cabinet(number="2", housing=housingA)
    cabn3 = Cabinet(number="3", housing=housingA)
    cabn4 = Cabinet(number="4", housing=housingB)
    cabn5 = Cabinet(number="5", housing=housingB)
    cabn6 = Cabinet(number="6", housing=housingB)

    les1 = LessonNumber(number=1)
    les2 = LessonNumber(number=2)
    les3 = LessonNumber(number=3)
    les4 = LessonNumber(number=4)
    les5 = LessonNumber(number=5)
    les6 = LessonNumber(number=6)
    les7 = LessonNumber(number=7)

    tchA = Teacher(first_name="Никита", middle_name="Платонович", second_name="Анисимов", work_exp=5)
    tchV = Teacher(first_name="Борис", middle_name="Романович", second_name="Веселов", work_exp=5)
    tchSh = Teacher(first_name="Устин", middle_name="Дмитриевич", second_name="Щербак", work_exp=5)
    tchC = Teacher(first_name="Евдоким", middle_name="Михайлович", second_name="Комиссаров", work_exp=5)

    timetblM1 = Timetable(day_week=monday,lesson_number=les1, klass=class5A, teacher=tchA, discipline=disRus,cabinet=cabn1)
    timetblM2 = Timetable(day_week=monday,lesson_number=les2, klass=class5A, teacher=tchSh, discipline=disAlgebra,cabinet=cabn3)
    timetblM3 = Timetable(day_week=monday,lesson_number=les3, klass=class5A, teacher=tchSh, discipline=disGeometry,cabinet=cabn3)
    timetblM4 = Timetable(day_week=monday,lesson_number=les4, klass=class5A, teacher=tchV, discipline=disBio,cabinet=cabn2)
    timetblM5 = Timetable(day_week=monday,lesson_number=les5, klass=class5A, teacher=tchA, discipline=disLiterature,cabinet=cabn1)
